baseURL = "https://hannaakym.com"
defaultContentLanguage = "ja"
enableEmoji = true
enableRobotsTXT = true
languageCode = "ja"
# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"
theme = "gokarna"
title = "Hanna Akiyama"


[params]
  dateFormat = "2006/01/02"
  togglePreviousAndNextButtons = true

  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/images/avatar.webp"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css" integrity="sha384-5TcZemv2l/9On385z///+d7MSYlvIEw9FuZTIdZ14vJLqWphw7e7ZPuOiCHJcFCP" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js" integrity="sha384-cMkvdD8LoxVzGF/RPUKAcvmm49FQ0oxwDF3BGKtDXcEc+T1b2N+teh/OJfpU0jr6" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js" integrity="sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

#  description = "Thinker / Translator / ?"
  description = "秋山 半名"
  footer = "Hanna Akiyama. All Rights Reserved."
  metaKeywords = ["ウィルフレッド・オーウェン", "第一次世界大戦"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages

  socialIcons = [
    {name = "bluesky", url = "https://bsky.app/profile/hannaakym.com"},
    {name = "orcid", url = "https://orcid.org/0009-0007-9160-3999"},
    {name = "github", url = "https://github.com/hannaakym"}
#    {name = "amazon", url = "https://kdp.amazon.co.jp/ja_JP/help/topic/G200644310"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Notes"
    pre = "<span data-feather='file-text'></span>"
    url = "/notes/"
    weight = 2

  [[menu.main]]
    name = "Work"
    pre = "<span data-feather='book-open'></span>"
    url = "/work/"
    weight = 3

  [[menu.main]]
    identifier = "email"
    pre = "<span data-feather='mail'></span>"
    url = "mailto:HannaAkym@gmail.com"
    weight = 4

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://buymeacoffee.com/hannaakym"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 6

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true
